### ISSUE TITLE
Video/PDF para info util de cursos/carreras

### ISSUE THREAD

**Issue by mcamelli** [mcamelli/excella#53]
Lo de los Cursos reenvía a la web, pero los Consejos de la Directora e Información Útil no reenvía a ninguna otra parte. Eso era algo que ya estaba consultado. ¿Cómo hacemos? Lo puedo cargar desde el administrador? SI ESTO ES LO QUE HABIAMOS PLANTEADO, CONSEJOS SE SUBIRIA UN VIDEO Y/O PDF Y EN INFO UTIL SE CARGARIA UN PDF. QUE PASO CON ESTO?? LO VIMOS EN LA ULTIMA REUNION QUE TUVIMOS.

**Comment by mcamelli** [comment]
Charlar con Celeste porque no esta en la SRS original, y segun lo charlado, si es nueva funcionalidad tenemos que presupuestar y cobrar.

**Comment by jluro** [comment]
Duplicate
