### ISSUE TITLE
 Cuando cierro sesión como usuario (alexhotze, por ejemplo), no como administrador, aparece la pantalla de Bienvenida al Panel de Control de Excella y Acceder al panel, para hacer el login ahí.

### ISSUE THREAD

**Issue by mcamelli** [mcamelli/excella#86]
-       Cuando cierro sesión como usuario (alexhotze, por ejemplo), no como administrador, aparece la pantalla de Bienvenida al Panel de Control de Excella y Acceder al panel, para hacer el login ahí.

http://excella-andreabruno.com:8080/aula/login?logout
Probé ingresar otra vez como usuario, y pude. Pero no está bien que sea eso lo que ve el alumno. Debería aparecer otro texto, como por ejemplo “Bienvenidoa/o a Mi Excella” y “Acceder a nuestra plataforma”, o algo así.

**Comment by jluro** [comment]
Se modifica logout para que vaya a la pagina principal de excella
